# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jaro/proj/sprout-2d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jaro/proj/sprout-2d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaro/proj/sprout-2d/CMakeFiles /Users/jaro/proj/sprout-2d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaro/proj/sprout-2d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sprout2d

# Build rule for target.
sprout2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sprout2d
.PHONY : sprout2d

# fast build rule for target.
sprout2d/fast:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/build
.PHONY : sprout2d/fast

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/Main.cpp.s
.PHONY : Main.cpp.s

src/GSM.o: src/GSM.cpp.o

.PHONY : src/GSM.o

# target to build an object file
src/GSM.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/GSM.cpp.o
.PHONY : src/GSM.cpp.o

src/GSM.i: src/GSM.cpp.i

.PHONY : src/GSM.i

# target to preprocess a source file
src/GSM.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/GSM.cpp.i
.PHONY : src/GSM.cpp.i

src/GSM.s: src/GSM.cpp.s

.PHONY : src/GSM.s

# target to generate assembly for a file
src/GSM.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/GSM.cpp.s
.PHONY : src/GSM.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/MenuState.o: src/MenuState.cpp.o

.PHONY : src/MenuState.o

# target to build an object file
src/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/MenuState.cpp.o
.PHONY : src/MenuState.cpp.o

src/MenuState.i: src/MenuState.cpp.i

.PHONY : src/MenuState.i

# target to preprocess a source file
src/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/MenuState.cpp.i
.PHONY : src/MenuState.cpp.i

src/MenuState.s: src/MenuState.cpp.s

.PHONY : src/MenuState.s

# target to generate assembly for a file
src/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/MenuState.cpp.s
.PHONY : src/MenuState.cpp.s

src/PlayState.o: src/PlayState.cpp.o

.PHONY : src/PlayState.o

# target to build an object file
src/PlayState.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/PlayState.cpp.o
.PHONY : src/PlayState.cpp.o

src/PlayState.i: src/PlayState.cpp.i

.PHONY : src/PlayState.i

# target to preprocess a source file
src/PlayState.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/PlayState.cpp.i
.PHONY : src/PlayState.cpp.i

src/PlayState.s: src/PlayState.cpp.s

.PHONY : src/PlayState.s

# target to generate assembly for a file
src/PlayState.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/PlayState.cpp.s
.PHONY : src/PlayState.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/sprout2d.dir/build.make CMakeFiles/sprout2d.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sprout2d"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... src/GSM.o"
	@echo "... src/GSM.i"
	@echo "... src/GSM.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/MenuState.o"
	@echo "... src/MenuState.i"
	@echo "... src/MenuState.s"
	@echo "... src/PlayState.o"
	@echo "... src/PlayState.i"
	@echo "... src/PlayState.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

